insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Kroger','Kroger','/images/cfbr2.1/Kroger.png','rgba(4,104,179,0.9)','rgba(255,255,255,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Central Market','CentralMarket','/images/cfbr2.1/centralmarket.png','rgba(255,255,255,0.9)','rgba(22,106,57,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('H-E-B','HEB','/images/cfbr2.1/H-E-B.png','rgba(238,40,36,0.9)','rgba(255,255,255,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Target','Target','/images/cfbr2.1/target.png','rgba(204,0,0,0.9)','rgba(255,255,255,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Walmart','Walmart','/images/cfbr2.1/Walmart.png','rgba(0,114,206,0.9)','rgba(253,187,48,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Albertsons','Albertsons','/images/cfbr2.1/albertsons.png','rgba(0, 159, 227,0.9)','rgba(0, 81, 161,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Safeway','Safeway','/images/cfbr2.1/safeway.png','rgba(214,35,42,0.9)','rgba(214,35,42,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Tom Thumb','TomThumb','/images/cfbr2.1/tomthumb.png','rgba(79,99,72,0.9)','rgba(255,255,255,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Whole Foods','WholeFoods','/images/cfbr2.1/wholefoods.png','rgba(0,103,75,0.9)','rgba(255,255,255,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Publix','Publix','/images/cfbr2.1/publix.png','rgba(62,144,45,0.9)','rgba(255,255,255,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Costco','Costco','/images/cfbr2.1/costco.png','rgba(0,93,170,0.9)','rgba(227,24,55,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Sam''s Club','SamsClub','/images/cfbr2.1/samsclub.png','rgba(93,151,50,0.9)','rgba(0,129,198,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('WinCo','WinCo','/images/cfbr2.1/winco.png','rgba(255, 228, 225,0.9)','rgba(255,255,255,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Winn-Dixie','WinnDixie','/images/cfbr2.1/winn-dixie.png','rgba(255, 236, 0,0.9)','rgba(216, 72, 51,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Piggly Wiggly','PigglyWiggly','/images/cfbr2.1/pigglywiggly.png','rgba(250, 205, 171,0.9)','rgba(255,255,255,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Brookshire''s','Brookshires','/images/cfbr2.1/brookshires.png','rgba(199, 0, 41,0.9)','rgba(80, 159, 84,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Brookshire Brothers','BrookshireBrothers','/images/cfbr2.1/brookshirebrothers.png','rgba(233, 150, 122,0.9)','rgba(255,255,255,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Braum''s','Braums','/images/cfbr2.1/braums.png','rgba177, 31, 115,0.9)','rgba(233, 214, 132,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Aldi','Aldi','/images/cfbr2.1/aldi.png','rgba(240,61,20,0.9)','rgba(0,31,120,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Lidl','Lidl','/images/cfbr2.1/lidl.png','rgba(255, 242, 0,0.9)','rgba(238, 28, 37,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Dollar Tree','DollarTree','/images/cfbr2.1/dollartree.png','rgba(89, 186, 41,0.9)','rgba(26, 24, 25,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Dollar General','DollarGeneral','/images/cfbr2.1/dollargeneral.png','rgba(202, 203, 204, 0.9)','rgba(255, 240, 0,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Big Lots','BigLots','/images/cfbr2.1/biglots.png','rgba(255,90,0,0.9) ','rgba(243,67,2,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('0.99 Only','0.99Only','/images/cfbr2.1/99conly.png','rgba(217, 35, 142,0.9)','rgba(0, 113, 198,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Family Dollar','FamilyDollar','/images/cfbr2.1/familydollar.png','rgba(238, 49, 36,0.9)','rgba(249, 157, 33,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Price Rite','PriceRite','/images/cfbr2.1/pricerite.png','rgba(255, 87, 0, 0.9)','rgba(33, 117, 155,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Shop Rite','ShopRite','/images/cfbr2.1/shoprite.png','rgba(72, 60, 50,0.9)','rgba(255,255,255,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Wegmans','Wegmans','/images/cfbr2.1/wegmans.png','rgba(0,0,0,0.9)','rgba(255,255,255,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Hy-Vee','HyVee','/images/cfbr2.1/hyvee.png','rgba(226,35,26,0.9);','rgba(255,255,255,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Meijer','Meijer','/images/cfbr2.1/meijer.png','rgba(10, 77, 140,0.9)','rgba(221, 19, 33,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Amazon Go','AmazonGo','/images/cfbr2.1/amazongo.png','rgba(255,153,0,0.9)','rgba(0,0,0,0.9)','{4}');
insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Trader Joe''s','TraderJoes','/images/cfbr2.1/traderjoes.png','rgba((210,18,66,0.9)','rgba(255,255,255,0.9)','{4}');
	insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Fresh Thyme','FreshThyme','/images/cfbr2.1/freshthyme.png','rgba(255, 214, 98,0.9)','rgba(1, 133, 65,0.9)','{4}');
	insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Dekalb Farmers Market','DekalbFarmersMarket','/images/cfbr2.1/DeKalb.png','rgba(165, 55, 253,0.9)','rgba(205,133,63,0.9)','{4}');
	insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Jewel-Osco','JewelOsco','/images/cfbr2.1/jewelosco.png','rgba(228,23,32,0.9)','rgba(0,0,0,0.9)','{4}');
	insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('La Michoacana','LaMichoacana','/images/cfbr2.1/lamichoacana.png','rgba(250,163,27,0.9)','rgba(255,0,0,0.9)','{4}');
	insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Canadian Tire','CanadianTire','/images/cfbr2.1/canadiantire.png','rgba(23, 167, 74,0.9)','rgba(237, 38, 38,0.9)','{4}');
	insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Kum and Go','KumandGo','/images/cfbr2.1/kumngo.png','rgba(245, 245, 220,0.9)','rgba(255,255,255,0.9)','{4}');
	insert into teams (tname, tshortname, logo, color_1, color_2, seasons) values ('Price Chopper','PriceChopper','/images/cfbr2.1/price-chopper.png','rgba(178, 34, 34,0.9)','rgba(255,255,255,0.9)','{4}');
insert into territories (id, name, region) values (1,'Colorado Springs',5);
insert into territories (id, name, region) values (2,'Akron',5);
insert into territories (id, name, region) values (3,'Tuscaloosa',5);
insert into territories (id, name, region) values (4,'Boone',5);
insert into territories (id, name, region) values (5,'Tucson',5);
insert into territories (id, name, region) values (6,'Tempe',5);
insert into territories (id, name, region) values (7,'Fayetteville',5);
insert into territories (id, name, region) values (8,'Jonesboro',5);
insert into territories (id, name, region) values (9,'West Point',5);
insert into territories (id, name, region) values (32,'Boca Raton',5);
insert into territories (id, name, region) values (62,'Lansing',5);
insert into territories (id, name, region) values (90,'New Jersey',5);
insert into territories (id, name, region) values (105,'San Marcos',5);
insert into territories (id, name, region) values (114,'Amherst',5);
insert into territories (id, name, region) values (117,'Salt Lake City',5);
insert into territories (id, name, region) values (40,'Hawai''i',5);
insert into territories (id, name, region) values (0,'Placeholder',5);
insert into territories (id, name, region) values (43,'Indiana',5);
insert into territories (id, name, region) values (10,'Auburn',5);
insert into territories (id, name, region) values (11,'Muncie',5);
insert into territories (id, name, region) values (12,'Waco',5);
insert into territories (id, name, region) values (13,'Boise',5);
insert into territories (id, name, region) values (14,'Boston',5);
insert into territories (id, name, region) values (15,'Bowling Green',5);
insert into territories (id, name, region) values (16,'Buffalo',5);
insert into territories (id, name, region) values (17,'Provo',5);
insert into territories (id, name, region) values (18,'Berkeley',5);
insert into territories (id, name, region) values (19,'Mount Pleasant',5);
insert into territories (id, name, region) values (20,'Alaska',5);
insert into territories (id, name, region) values (21,'Charlotte',5);
insert into territories (id, name, region) values (22,'Cincinnati',5);
insert into territories (id, name, region) values (23,'Clemson',5);
insert into territories (id, name, region) values (24,'Myrtle Beach',5);
insert into territories (id, name, region) values (25,'Boulder',5);
insert into territories (id, name, region) values (26,'Fort Collins',5);
insert into territories (id, name, region) values (27,'Connecticut',5);
insert into territories (id, name, region) values (28,'Durham',5);
insert into territories (id, name, region) values (29,'Greenville',5);
insert into territories (id, name, region) values (30,'Ypsilanti',5);
insert into territories (id, name, region) values (31,'Gainesville',5);
insert into territories (id, name, region) values (33,'University Park',5);
insert into territories (id, name, region) values (34,'Tallahassee',5);
insert into territories (id, name, region) values (35,'Fresno',5);
insert into territories (id, name, region) values (36,'Athens',5);
insert into territories (id, name, region) values (37,'Statesboro',5);
insert into territories (id, name, region) values (38,'South Atlanta',5);
insert into territories (id, name, region) values (39,'North Atlanta',5);
insert into territories (id, name, region) values (41,'East Houston',5);
insert into territories (id, name, region) values (42,'Champaign',5);
insert into territories (id, name, region) values (44,'Iowa City',5);
insert into territories (id, name, region) values (45,'Ames',5);
insert into territories (id, name, region) values (46,'Lawrence',5);
insert into territories (id, name, region) values (47,'Manhattan',5);
insert into territories (id, name, region) values (48,'Kent',5);
insert into territories (id, name, region) values (49,'Lexington',5);
insert into territories (id, name, region) values (50,'Lynchburg',5);
insert into territories (id, name, region) values (51,'Lafayette',5);
insert into territories (id, name, region) values (52,'Monroe',5);
insert into territories (id, name, region) values (53,'Ruston',5);
insert into territories (id, name, region) values (54,'Louisville',5);
insert into territories (id, name, region) values (55,'Baton Rouge',5);
insert into territories (id, name, region) values (56,'Huntington',5);
insert into territories (id, name, region) values (57,'College Park',5);
insert into territories (id, name, region) values (58,'Memphis',5);
insert into territories (id, name, region) values (59,'Miami',5);
insert into territories (id, name, region) values (60,'Miami Valley',5);
insert into territories (id, name, region) values (61,'Ann Arbor',5);
insert into territories (id, name, region) values (63,'Murfreesboro',5);
insert into territories (id, name, region) values (64,'Minnesota',5);
insert into territories (id, name, region) values (65,'Starkville',5);
insert into territories (id, name, region) values (66,'Missouri',5);
insert into territories (id, name, region) values (67,'Annapolis',5);
insert into territories (id, name, region) values (68,'Raleigh',5);
insert into territories (id, name, region) values (69,'Nebraska',5);
insert into territories (id, name, region) values (70,'Reno',5);
insert into territories (id, name, region) values (71,'Albuquerque',5);
insert into territories (id, name, region) values (72,'Las Cruces',5);
insert into territories (id, name, region) values (73,'Chapel Hill',5);
insert into territories (id, name, region) values (74,'DeKalb',5);
insert into territories (id, name, region) values (75,'Denton',5);
insert into territories (id, name, region) values (76,'Chicago',5);
insert into territories (id, name, region) values (77,'South Bend',5);
insert into territories (id, name, region) values (78,'Hocking Hills',5);
insert into territories (id, name, region) values (79,'Columbus',5);
insert into territories (id, name, region) values (80,'Norman',5);
insert into territories (id, name, region) values (81,'Stillwater',5);
insert into territories (id, name, region) values (82,'Norfolk',5);
insert into territories (id, name, region) values (83,'Oxford',5);
insert into territories (id, name, region) values (84,'Eugene',5);
insert into territories (id, name, region) values (85,'Corvallis',5);
insert into territories (id, name, region) values (86,'Happy Valley',5);
insert into territories (id, name, region) values (87,'Pittsburgh',5);
insert into territories (id, name, region) values (88,'West Lafayette',5);
insert into territories (id, name, region) values (89,'West Houston',5);
insert into territories (id, name, region) values (91,'San Diego',5);
insert into territories (id, name, region) values (93,'Dallas',5);
insert into territories (id, name, region) values (94,'Mobile',5);
insert into territories (id, name, region) values (95,'Columbia',5);
insert into territories (id, name, region) values (96,'Hattiesburg',5);
insert into territories (id, name, region) values (97,'Tampa',5);
insert into territories (id, name, region) values (98,'Palo Alto',5);
insert into territories (id, name, region) values (99,'Syracuse',5);
insert into territories (id, name, region) values (100,'Fort Worth',5);
insert into territories (id, name, region) values (101,'Philadelphia',5);
insert into territories (id, name, region) values (102,'Knoxville',5);
insert into territories (id, name, region) values (103,'Austin',5);
insert into territories (id, name, region) values (104,'College Station',5);
insert into territories (id, name, region) values (106,'Lubbock',5);
insert into territories (id, name, region) values (107,'Toledo',5);
insert into territories (id, name, region) values (108,'Troy',5);
insert into territories (id, name, region) values (109,'New Orleans',5);
insert into territories (id, name, region) values (110,'Tulsa',5);
insert into territories (id, name, region) values (111,'Birmingham',5);
insert into territories (id, name, region) values (112,'Orlando',5);
insert into territories (id, name, region) values (113,'North Los Angeles',5);
insert into territories (id, name, region) values (115,'Las Vegas',5);
insert into territories (id, name, region) values (116,'South Los Angeles',5);
insert into territories (id, name, region) values (118,'Logan',5);
insert into territories (id, name, region) values (119,'El Paso',5);
insert into territories (id, name, region) values (92,'San Jose',5);
insert into territories (id, name, region) values (120,'San Antonio',5);
insert into territories (id, name, region) values (121,'Nashville',5);
insert into territories (id, name, region) values (122,'Charlottesville',5);
insert into territories (id, name, region) values (123,'Blacksburg',5);
insert into territories (id, name, region) values (124,'Winston-Salem',5);
insert into territories (id, name, region) values (125,'Seattle',5);
insert into territories (id, name, region) values (126,'Pullman',5);
insert into territories (id, name, region) values (127,'Western Kentucky',5);
insert into territories (id, name, region) values (128,'Kalamazoo',5);
insert into territories (id, name, region) values (129,'Morgantown',5);
insert into territories (id, name, region) values (130,'Wisconsin',5);
insert into territories (id, name, region) values (131,'Wyoming',5);

